# Generated by Django 5.2.11 on 2026-02-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Video link', max_length=500, null=True)),
                ('category', models.CharField(choices=[('SUBSIDY', 'Subsidy'), ('LOAN', 'Loan'), ('INSURANCE', 'Insurance'), ('TRAINING', 'Training'), ('MARKETING', 'Marketing')], default='SUBSIDY', max_length=20)),
                ('target_districts', models.JSONField(help_text='List of districts where this scheme is applicable')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
