# Generated by Django 5.2.11 on 2026-02-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='district',
            field=models.CharField(choices=[('AHMEDNAGAR', 'Ahmednagar (Ahilyanagar)'), ('AKOLA', 'Akola'), ('AMRAVATI', 'Amravati'), ('AURANGABAD', 'Aurangabad (Chhatrapati Sambhajinagar)'), ('BEED', 'Beed'), ('BHANDARA', 'Bhandara'), ('BULDHANA', 'Buldhana'), ('CHANDRAPUR', 'Chandrapur'), ('DHULE', 'Dhule'), ('GADCHIROLI', 'Gadchiroli'), ('GONDIA', 'Gondia'), ('HINGOLI', 'Hingoli'), ('JALGAON', 'Jalgaon'), ('JALNA', 'Jalna'), ('KOLHAPUR', 'Kolhapur'), ('LATUR', 'Latur'), ('MUMBAI_CITY', 'Mumbai City'), ('MUMBAI_SUBURBAN', 'Mumbai Suburban'), ('NAGPUR', 'Nagpur'), ('NANDED', 'Nanded'), ('NANDURBAR', 'Nandurbar'), ('NASHIK', 'Nashik'), ('OSMANABAD', 'Osmanabad (Dharashiv)'), ('PALGHAR', 'Palghar'), ('PARBHANI', 'Parbhani'), ('PUNE', 'Pune'), ('RAIGAD', 'Raigad'), ('RATNAGIRI', 'Ratnagiri'), ('SANGLI', 'Sangli'), ('SATARA', 'Satara'), ('SINDHUDURG', 'Sindhudurg'), ('SOLAPUR', 'Solapur'), ('THANE', 'Thane'), ('WARDHA', 'Wardha'), ('WASHIM', 'Washim'), ('YAVATMAL', 'Yavatmal')], max_length=50),
        ),
    ]
