# Generated by Django 5.2.11 on 2026-02-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0005_watchhistory_watchlater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='target_districts',
        ),
    ]
