# Generated by Django 5.2.11 on 2026-02-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0006_remove_scheme_target_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Official government application link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='benefit_amount',
            field=models.CharField(blank=True, help_text='e.g., ₹6,000/वर्ष or 50% सब्सिडी', max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='scheme_thumbnails/'),
        ),
    ]
