# Generated by Django 5.2.11 on 2026-02-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0007_scheme_apply_url_scheme_benefit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='video_url',
        ),
        migrations.AddField(
            model_name='scheme',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, AVI, MOV)', null=True, upload_to='scheme_videos/'),
        ),
    ]
